# Use a lightweight Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Install curl
RUN apt-get update && apt-get install -y curl && apt-get clean

# Copy the app file
COPY backend.py /app

# Install Flask
RUN pip install Flask

# Expose the application port
EXPOSE 5001

# Run the Flask app
CMD ["python", "backend.py"]
