apiVersion: v1
kind: Service
metadata:
  name: flask-load-balancer-service
spec:
  selector:
    app: flask-load-balancer
  ports:
  - protocol: TCP
    port: 30080
    targetPort: 5000
  type: NodePort
